image: registry.esss.lu.se/afonsomukai/docker-registry:1.0.0

stages:
  - check
  - test

flake8:
  tags:
    - docker
  stage: check
  script:
    - python -m flake8

black:
  tags:
    - docker
  stage: check
  script:
    - python -m black --check .

mypy:
  tags:
    - docker
  stage: check
  script:
    - python -m mypy .

test:
  tags:
    - docker
  stage: test
  script:
    - python -m pytest
