default:
  tags:
    - docker

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

stages:
  - checks
  - test
  - integration

black:
  image: python:3.9-slim
  stage: checks
  script:
    - pip install -r requirements-dev.txt --no-cache-dir
    - python -m black --check .

flake8:
  image: python:3.9-slim
  stage: checks
  script:
    - pip install -r requirements-dev.txt --no-cache-dir
    - python -m flake8

mypy:
  image: python:3.9-slim
  stage: checks
  script:
    - pip install -r requirements-dev.txt --no-cache-dir
    - python -m mypy .

test:
  image: python:3.9-slim
  stage: test
  script:
    - pip install -r requirements-dev.txt --no-cache-dir
    - python -m tox -- --cov=forwarder --cov-report=term --cov-report=xml --junitxml=test-output.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - test-output.xml
      - coverage.xml
    reports:
      junit: test-output.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

.integration-tests:
  stage: integration
  image: docker:latest
  before_script:
    - cd integration_tests
    - ./setup.sh
  after_script:
    - cd integration_tests
    - ./teardown.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  variables:
    FORWARDER_ZOOKEEPER_CONTAINER_NAME: zookeeper-$CI_JOB_ID
    FORWARDER_KAFKA_CONTAINER_NAME: kafka1-$CI_JOB_ID
    FORWARDER_SIMPLEIOC_CONTAINER_NAME: simpleioc-$CI_JOB_ID
    FORWARDER_FORWARDER_CONTAINER_NAME: forwarder-$CI_JOB_ID
    HTTP_PROXY: $ESS_HTTP_PROXY
    HTTPS_PROXY: $ESS_HTTP_PROXY

contract-tests:
  extends: .integration-tests
  script:
    - ./run-contract-tests.sh
  artifacts:
    paths:
      - integration_tests/ContractTestsOutput.xml
    reports:
      junit: integration_tests/ContractTestsOutput.xml

smoke-tests:
  extends: .integration-tests
  script:
    - ./run-smoke-tests.sh
  artifacts:
    paths:
      - integration_tests/SmokeTestsOutput.xml
    reports:
      junit: integration_tests/SmokeTestsOutput.xml
