workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

variables:
  UV_VERSION: "0.9"
  PYTHON_VERSION: "3.14"
  BASE_LAYER: trixie-slim
  # GitLab CI creates a separate mountpoint for the build directory,
  # so we need to copy instead of using hard links.
  UV_LINK_MODE: copy

default:
  tags:
    - docker
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER

stages:
  - checks
  - test
  - integration

black:
  stage: checks
  script:
    - uvx black --check .

flake8:
  stage: checks
  script:
    - uvx ruff check

mypy:
  stage: checks
  script:
    - uv run mypy .

test:
  stage: test
  script:
    - uv run pytest --cov=forwarder --cov-report=term --cov-report=xml --junitxml=test-output.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - test-output.xml
      - coverage.xml
    reports:
      junit: test-output.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

.integration-tests:
  stage: integration
  image: docker:28
  before_script:
    - cd integration_tests
    - ./setup.sh
  after_script:
    - cd integration_tests
    - ./teardown.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  variables:
    FORWARDER_ZOOKEEPER_CONTAINER_NAME: zookeeper-$CI_JOB_ID
    FORWARDER_KAFKA_CONTAINER_NAME: kafka1-$CI_JOB_ID
    FORWARDER_SIMPLEIOC_CONTAINER_NAME: simpleioc-$CI_JOB_ID
    FORWARDER_FORWARDER_CONTAINER_NAME: forwarder-$CI_JOB_ID
    HTTP_PROXY: $ESS_HTTP_PROXY
    HTTPS_PROXY: $ESS_HTTP_PROXY

contract-tests:
  extends: .integration-tests
  script:
    - ./run-contract-tests.sh
  artifacts:
    paths:
      - integration_tests/ContractTestsOutput.xml
    reports:
      junit: integration_tests/ContractTestsOutput.xml

smoke-tests:
  extends: .integration-tests
  script:
    - ./run-smoke-tests.sh
  artifacts:
    paths:
      - integration_tests/SmokeTestsOutput.xml
    reports:
      junit: integration_tests/SmokeTestsOutput.xml
