image: registry.esss.lu.se/afonsomukai/docker-registry:1.0.0

stages:
  - check
  - test

static:
  tags:
    - docker
  stage: check
  script:
    - scl enable rh-python38 -- python --version
    - scl enable rh-python38 -- python -m pip install --user -r requirements-dev.txt
    - scl enable rh-python38 -- python -m black --check .
    - scl enable rh-python38 -- python -m flake8
    - scl enable rh-python38 -- python -m mypy .

test:
  tags:
    - docker
  stage: test
  script:
    - pyenv global 3.8 3.9 3.10
    - pyenv versions
    - export PATH="/home/jenkins/.pyenv/shims:$PATH"
    - echo $PATH
    - python -m tox -- --cov=forwarder --cov-report=xml --junitxml=TestResults.xml
