image: registry.esss.lu.se/afonsomukai/docker-registry:1.0.0

stages:
  - check
  - test

static:
  tags:
    - docker
  stage: check
  script:
    - scl enable rh-python38 -- python -m pip install --user -r requirements.txt
    - scl enable rh-python38 -- python -m flake8
    - scl enable rh-python38 -- python -m black --check .
    - scl enable rh-python38 -- python -m mypy .

test:
  tags:
    - docker
  stage: test
  script:
    - scl enable rh-python38 -- python -m pip install --user -r requirements.txt
    - scl enable rh-python38 -- python -m pytest
