image: registry.esss.lu.se/ecdc/ess-dmsc/docker-centos7-build-node:12.0.0

before_script:
  - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_TOKEN registry.esss.lu.se

stages:
  - check
  - test

flake8:
  tags:
    - docker
  stage: check
  script:
    - python -m flake8

black:
  tags:
    - docker
  stage: check
  script:
    - python -m black --check .

mypy:
  tags:
    - docker
  stage: check
  script:
    - python -m mypy .

test:
  tags:
    - docker
  stage: test
  script:
    - python -m pytest
