[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ecdc-forwarder"
version = "2.2.1-rc.1"
urls = {homepage="https://github.com/ess-dmsc/forwarder", repository="https://github.com/ess-dmsc/forwarder"}
license = { file="LICENSE" }
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "caproto",
    "p4p",
    "confluent_kafka",
    "graphyte",
    "numpy<2",
    "ConfigArgParse",
    "ess-streaming-data-types",
    "tomli",
    "prometheus-client",
    "kafka-python>=2.3.0",
]

[dependency-groups]
dev = [
    "pip-tools",
    "mypy",
    "black",
    "pytest",
    "isort",
    "pre-commit",
    "pytest-cov",
]

[project.scripts]
forwarder-launch = "forwarder.scripts.run:main"

[tool.setuptools.packages.find]
include=["forwarder"]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
markers = [
    "epics_protocol: (EpicsProtocol) The protocol used for the test",
    "schema: (str) The streaming-data-type of the test",
    "serialiser_update_period_ms: (int) Update period (ms) for any created Serialiser",
]
testpaths = [
    "tests",
]
addopts = "-s"
junit_family = "xunit2"

[tool.coverage.run]
branch = true
source = ["forwarder"]

[tool.coverage.report]
show_missing = true

[tool.mypy]
check_untyped_defs = true
plugins = ["numpy.typing.mypy_plugin"]

[[tool.mypy.overrides]]
module = "confluent_kafka.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "streaming_data_types.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "numpy.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "caproto.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pytest.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "p4p.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "configargparse.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "setuptools.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "flatbuffers.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "integration_tests.*"
ignore_errors = true

[[tool.mypy.overrides]]
module = "forwarder.repeat_timer.*"
ignore_errors = true

[[tool.mypy.overrides]]
module = "contract_tests.*"
ignore_errors = true

[[tool.mypy.overrides]]
module = "integration_tests.smoke_tests.*"
ignore_errors = true

[[tool.mypy.overrides]]
module = "attr.*"
ignore_errors = true

[[tool.uv.index]]
name = "ecdc-pypi"
url = "https://artifactory.esss.lu.se/artifactory/api/pypi/ecdc-pypi/simple"
publish-url = "https://artifactory.esss.lu.se/artifactory/api/pypi/ecdc-pypi"
default = true
