version: '3.7'

services:
  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    depends_on:
      - zookeeper
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_BROKER_ID: 0
      KAFKA_CREATE_TOPICS: "test_write_and_read_message:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
    image: zookeeper:3.4

  simpleioc:
    image: dockerregistry.esss.dk/ecdc_group/build-node-images/simpleioc:latest
    depends_on:
      - kafka
    tty: true
    ports:
      - "5064:5065"
      - "5075:5076"
      - "5064:5064/udp"
      - "5076:5076/udp"